# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Game.create(name: "Schmega Schman", console: "Schintendo Entertainment Schystem", release_date: "December 17, 1987")
Game.create(name: "Schmega Schman 2", console: "Schintendo Entertainment Schystem", release_date: "December 24, 1988")
Game.create(name: "Schmega Schman 3", console: "Schintendo Entertainment Schystem", release_date: "September 28, 1990")
Game.create(name: "Schmega Schman 4", console: "Schintendo Entertainment Schystem", release_date: "December 6, 1991")
Game.create(name: "Schmega Schman 5", console: "Schintendo Entertainment Schystem", release_date: "December 4, 1992")
Game.create(name: "Schmega Schman 6", console: "Schintendo Entertainment Schystem", release_date: "November 5, 1993")
Game.create(name: "Schmega Schman 7", console: "Schuper Schintendo Entertainment Schystem", release_date: "March 24, 1995")
Game.create(name: "Schmega Schman 8", console: "PlaySchtation", release_date: "December 17, 1996")
Game.create(name: "Schmega Schman 9", console: "Schwii", release_date: "September 22, 2008")
Game.create(name: "Schmega Schman 10", console: "Schwii", release_date: "March 1, 2010")
Game.create(name: "Schmega Schman 11", console: "Schintendo Schwitch", release_date: "October 2, 2018")

RobotSchmaster.create(name: "Cut Schman", serial_number: "DLN.003", weapon: "Rolling Cutter", weakness: "Super Arm", game_id: 1)
RobotSchmaster.create(name: "Guts Schman", serial_number: "DLN.004", weapon: "Super Arm", weakness: "Hyper Bomb", game_id: 1)
RobotSchmaster.create(name: "Ice Schman", serial_number: "DLN.005", weapon: "Ice Slasher", weakness: "Thunder Beam", game_id: 1)
RobotSchmaster.create(name: "Bomb Schman", serial_number: "DLN.006", weapon: "Hyper Bomb", weakness: "Fire Storm", game_id: 1)
RobotSchmaster.create(name: "Fire Schman", serial_number: "DLN.007", weapon: "Fire Storm", weakness: "Ice Slasher", game_id: 1)
RobotSchmaster.create(name: "Elec Schman", serial_number: "DLN.008", weapon: "Thunder Beam", weakness: "Rolling Cutter", game_id: 1)

RobotSchmaster.create(name: "Metal Schman", serial_number: "DWN.009", weapon: "Metal Blade", weakness: "Metal Blade", game_id: 2)
RobotSchmaster.create(name: "Air Schman", serial_number: "DWN.010", weapon: "Air Shooter", weakness: "Leaf Shield", game_id: 2)
RobotSchmaster.create(name: "Bubble Schman", serial_number: "DWN.011", weapon: "Bubble Lead", weakness: "Metal Blade", game_id: 2)
RobotSchmaster.create(name: "Quick Schman", serial_number: "DWN.012", weapon: "Quick Boomerang", weakness: "Flash Stopper", game_id: 2)
RobotSchmaster.create(name: "Crash Schman", serial_number: "DWN.013", weapon: "Crash Bomber", weakness: "Air Shooter", game_id: 2)
RobotSchmaster.create(name: "Flash Schman", serial_number: "DWN.014", weapon: "Flash Stopper", weakness: "Metal Blade", game_id: 2)
RobotSchmaster.create(name: "Heat Schman", serial_number: "DWN.015", weapon: "Atomic Fire", weakness: "Bubble Lead", game_id: 2)
RobotSchmaster.create(name: "Wood Schman", serial_number: "DWN.016", weapon: "Leaf Shield", weakness: "Atomic Fire", game_id: 2)

RobotSchmaster.create(name: "Needle Schman", serial_number: "DWN.017", weapon: "Needle Cannon", weakness: "Gemini Laser", game_id: 3)
RobotSchmaster.create(name: "Magnet Schman", serial_number: "DWN.018", weapon: "Magnet Missile", weakness: "Spark Shock", game_id: 3)
RobotSchmaster.create(name: "Gemini Schman", serial_number: "DWN.019", weapon: "Gemini Laser", weakness: "Search Snake", game_id: 3)
RobotSchmaster.create(name: "Hard Schman", serial_number: "DWN.020", weapon: "Hard Knuckle", weakness: "Magnet Missile", game_id: 3)
RobotSchmaster.create(name: "Top Schman", serial_number: "DWN.021", weapon: "Top Spin", weakness: "Hard Knuckle", game_id: 3)
RobotSchmaster.create(name: "Snake Schman", serial_number: "DWN.022", weapon: "Search Snake", weakness: "Needle Cannon", game_id: 3)
RobotSchmaster.create(name: "Spark Schman", serial_number: "DWN.023", weapon: "Spark Shock", weakness: "Shadow Blade", game_id: 3)
RobotSchmaster.create(name: "Shadow Schman", serial_number: "DWN.024", weapon: "Shadow Blade", weakness: "Top Spin", game_id: 3)

RobotSchmaster.create(name: "Bright Schman", serial_number: "DWN.025", weapon: "Flash Stopper", weakness: "Rain Flush", game_id: 4)
RobotSchmaster.create(name: "Toad Schman", serial_number: "DWN.026", weapon: "Rain Flush", weakness: "Drill Bomb", game_id: 4)
RobotSchmaster.create(name: "Drill Schman", serial_number: "DWN.027", weapon: "Drill Bomb", weakness: "Dive Missile", game_id: 4)
RobotSchmaster.create(name: "Pharaoh Schman", serial_number: "DWN.028", weapon: "Pharaoh Shot", weakness: "Flash Stopper", game_id: 4)
RobotSchmaster.create(name: "Ring Schman", serial_number: "DWN.029", weapon: "Ring Boomerang", weakness: "Pharaoh Shot", game_id: 4)
RobotSchmaster.create(name: "Dust Schman", serial_number: "DWN.030", weapon: "Dust Crusher", weakness: "Ring Boomerang", game_id: 4)
RobotSchmaster.create(name: "Dive Schman", serial_number: "DWN.031", weapon: "Dive Missile", weakness: "Skull Barrier", game_id: 4)
RobotSchmaster.create(name: "Skull Schman", serial_number: "DWN.032", weapon: "Skull Barrier", weakness: "Dust Crusher", game_id: 4)

RobotSchmaster.create(name: "Gravity Schman", serial_number: "DWN.033", weapon: "Gravity Hold", weakness: "Star Crash", game_id: 5)
RobotSchmaster.create(name: "Wave Schman", serial_number: "DWN.034", weapon: "Water Wave", weakness: "Charge Kick", game_id: 5)
RobotSchmaster.create(name: "Stone Schman", serial_number: "DWN.035", weapon: "Power Stone", weakness: "Napalm Bomb", game_id: 5)
RobotSchmaster.create(name: "Gyro Schman", serial_number: "DWN.036", weapon: "Gyro Attack", weakness: "Gravity Hold", game_id: 5)
RobotSchmaster.create(name: "Star Schman", serial_number: "DWN.037", weapon: "Star Crash", weakness: "Water Wave", game_id: 5)
RobotSchmaster.create(name: "Charge Schman", serial_number: "DWN.038", weapon: "Charge Kick", weakness: "Power Stone", game_id: 5)
RobotSchmaster.create(name: "Napalm Schman", serial_number: "DWN.039", weapon: "Napalm Bomb", weakness: "Crystal Eye", game_id: 5)
RobotSchmaster.create(name: "Crystal Schman", serial_number: "DWN.040", weapon: "Crystal Eye", weakness: "Gyro Attack", game_id: 5)

RobotSchmaster.create(name: "Blizzard Schman", serial_number: "DWN.041", weapon: "Blizzard Attack", weakness: "Flame Blast", game_id: 6)
RobotSchmaster.create(name: "Centaur Schman", serial_number: "DWN.042", weapon: "Centaur Flash", weakness: "Knight Crush", game_id: 6)
RobotSchmaster.create(name: "Flame Schman", serial_number: "DWN.043", weapon: "Flame Blast", weakness: "Wind Storm", game_id: 6)
RobotSchmaster.create(name: "Knight Schman", serial_number: "DWN.044", weapon: "Knight Crush", weakness: "Yamato Spear", game_id: 6)
RobotSchmaster.create(name: "Plant Schman", serial_number: "DWN.045", weapon: "Plant Barrier", weakness: "Blizzard Attack", game_id: 6)
RobotSchmaster.create(name: "Tomahawk Schman", serial_number: "DWN.046", weapon: "Silver Tomahawk", weakness: "Plant Barrier", game_id: 6)
RobotSchmaster.create(name: "Wind Schman", serial_number: "DWN.047", weapon: "Wind Storm", weakness: "Centaur Flash", game_id: 6)
RobotSchmaster.create(name: "Yamato Schman", serial_number: "DWN.048", weapon: "Yamato Spear", weakness: "Silver Tomahawk", game_id: 6)

RobotSchmaster.create(name: "Freeze Schman", serial_number: "DWN.049", weapon: "Freeze Cracker", weakness: "Junk Shield", game_id: 7)
RobotSchmaster.create(name: "Junk Schman", serial_number: "DWN.050", weapon: "Junk Shield", weakness: "Thunder Bolt", game_id: 7)
RobotSchmaster.create(name: "Burst Schman", serial_number: "DWN.051", weapon: "Danger Wrap", weakness: "Scorch Wheel", game_id: 7)
RobotSchmaster.create(name: "Cloud Schman", serial_number: "DWN.052", weapon: "Thunder Bolt", weakness: "Danger Wrap", game_id: 7)
RobotSchmaster.create(name: "Spring Schman", serial_number: "DWN.053", weapon: "Wild Coil", weakness: "Slash Claw", game_id: 7)
RobotSchmaster.create(name: "Slash Schman", serial_number: "DWN.054", weapon: "Slash Claw", weakness: "Freeze Cracker", game_id: 7)
RobotSchmaster.create(name: "Shade Schman", serial_number: "DWN.055", weapon: "Noise Crush", weakness: "Wild Coil", game_id: 7)
RobotSchmaster.create(name: "Turbo Schman", serial_number: "DWN.056", weapon: "Scorch Wheel", weakness: "Noise Crush", game_id: 7)

RobotSchmaster.create(name: "Tengu Schman", serial_number: "DWN.057", weapon: "Tornado Hold", weakness: "Ice Wave", game_id: 8)
RobotSchmaster.create(name: "Astro Schman", serial_number: "DWN.058", weapon: "Astro Crush", weakness: "Homing Sniper", game_id: 8)
RobotSchmaster.create(name: "Sword Schman", serial_number: "DWN.059", weapon: "Flame Sword", weakness: "Water Balloon", game_id: 8)
RobotSchmaster.create(name: "Clown Schman", serial_number: "DWN.060", weapon: "Thunder Claw", weakness: "Tornado Hold", game_id: 8)
RobotSchmaster.create(name: "Search Schman", serial_number: "DWN.061", weapon: "Homing Sniper", weakness: "Flame Sword", game_id: 8)
RobotSchmaster.create(name: "Frost Schman", serial_number: "DWN.062", weapon: "Ice Wave", weakness: "Flash Bomb", game_id: 8)
RobotSchmaster.create(name: "Grenade Schman", serial_number: "DWN.063", weapon: "Flash Bomb", weakness: "Thunder Claw", game_id: 8)
RobotSchmaster.create(name: "Aqua Schman", serial_number: "DWN.064", weapon: "Water Balloon", weakness: "Astro Crush", game_id: 8)

RobotSchmaster.create(name: "Concrete Schman", serial_number: "DLN.065", weapon: "Concrete Shot", weakness: "Laser Trident", game_id: 9)
RobotSchmaster.create(name: "Tornado Schman", serial_number: "DLN.066", weapon: "Tornado Blow", weakness: "Plug Ball", game_id: 9)
RobotSchmaster.create(name: "Splash Schwoman", serial_number: "DLN.067", weapon: "Laser Trident", weakness: "Hornet Chaser", game_id: 9)
RobotSchmaster.create(name: "Plug Schman", serial_number: "DLN.068", weapon: "Plug Ball", weakness: "Jewel Satellite", game_id: 9)
RobotSchmaster.create(name: "Jewel Schman", serial_number: "DLN.069", weapon: "Jewel Satellite", weakness: "Black Hole Bomb", game_id: 9)
RobotSchmaster.create(name: "Hornet Schman", serial_number: "DLN.070", weapon: "Hornet Chaser", weakness: "Magma Bazooka", game_id: 9)
RobotSchmaster.create(name: "Magma Schman", serial_number: "DLN.071", weapon: "Magma Bazooka", weakness: "Tornado Blow", game_id: 9)
RobotSchmaster.create(name: "Galaxy Schman", serial_number: "DLN.072", weapon: "Black Hole Bomb", weakness: "Concrete Shot", game_id: 9)

RobotSchmaster.create(name: "Blade Schman", serial_number: "DWN.073", weapon: "Triple Blade", weakness: "Commando Bomb", game_id: 10)
RobotSchmaster.create(name: "Pump Schman", serial_number: "DWN.074", weapon: "Water Shield", weakness: "Thunder Wool", game_id: 10)
RobotSchmaster.create(name: "Commando Schman", serial_number: "DWN.075", weapon: "Commando Bomb", weakness: "Wheel Cutter", game_id: 10)
RobotSchmaster.create(name: "Chill Schman", serial_number: "DWN.076", weapon: "Chill Spike", weakness: "Solar Blaze", game_id: 10)
RobotSchmaster.create(name: "Sheep Schman", serial_number: "DWN.077", weapon: "Thunder Wool", weakness: "Rebound Striker", game_id: 10)
RobotSchmaster.create(name: "Strike Schman", serial_number: "DWN.078", weapon: "Rebound Striker", weakness: "Triple Blade", game_id: 10)
RobotSchmaster.create(name: "Nitro Schman", serial_number: "DWN.079", weapon: "Wheel Cutter", weakness: "Chill Spike", game_id: 10)
RobotSchmaster.create(name: "Solar Schman", serial_number: "DWN.080", weapon: "Solar Blaze", weakness: "Water Shield", game_id: 10)

RobotSchmaster.create(name: "Block Schman", serial_number: "DWN.081", weapon: "Block Dropper", weakness: "Chain Blast", game_id: 11)
RobotSchmaster.create(name: "Fuse Schman", serial_number: "DWN.082", weapon: "Scramble Thunder", weakness: "Bounce Ball", game_id: 11)
RobotSchmaster.create(name: "Blast Schman", serial_number: "DWN.083", weapon: "Chain Blast", weakness: "Blazing Torch", game_id: 11)
RobotSchmaster.create(name: "Acid Schman", serial_number: "DWN.084", weapon: "Acid Barrier", weakness: "Block Dropper", game_id: 11)
RobotSchmaster.create(name: "Tundra Schman", serial_number: "DWN.085", weapon: "Tundra Storm", weakness: "Scramble Thunder", game_id: 11)
RobotSchmaster.create(name: "Torch Schman", serial_number: "DWN.086", weapon: "Blazing Torch", weakness: "Tundra Storm", game_id: 11)
RobotSchmaster.create(name: "Impact Schman", serial_number: "DWN.087", weapon: "Pile Driver", weakness: "Acid Barrier", game_id: 11)
RobotSchmaster.create(name: "Bounce Schman", serial_number: "DWN.088", weapon: "Bounce Ball", weakness: "Pile Driver", game_id: 11)